FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY ["httpNodeView/httpNodeView.csproj", "httpNodeView/"]
RUN dotnet restore "httpNodeView/httpNodeView.csproj"

COPY ["httpNodeView/", "httpNodeView/"]
COPY ["raftLibrary/", "raftLibrary/"]
RUN dotnet build "httpNodeView/httpNodeView.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "httpNodeView/httpNodeView.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app
COPY --from=publish /app/publish .

EXPOSE 5003
ENV ASPNETCORE_URLS=http://+:5003

ENTRYPOINT ["dotnet", "httpNodeView.dll"]
